  menu6dd08874f83507e9c7b23f1a46b7fa7c = {      {"Lokalize", "lokalize "},
  }

  menue9f65fa4000d038efa0cdff8bb824632 = {      {"KImageMapEditor", "kimagemapeditor -caption KImageMapEditor "},
      {"KLinkStatus", "klinkstatus   -caption KLinkStatus"},
  }

 menu330f49df8243756a8a4dc7f7f7ee6dfe = {    {"Translation", menu6dd08874f83507e9c7b23f1a46b7fa7c},
    {"Web Development", menue9f65fa4000d038efa0cdff8bb824632},
     {"Akonadi Console", "akonadiconsole"},
     {"Android Studio", "/usr/share/android-studio/bin/studio.sh"},
     {"ArgoUML", "argouml", "/usr/share/pixmaps/argouml.png" },
     {"Atom", "/usr/bin/atom "},
     {"CMake", "cmake-gui "},
     {"Cervisia", "cervisia -caption Cervisia  "},
     {"Cuttlefish", "cuttlefish"},
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.png" },
     {"Geany", "geany "},
     {"Glade", "glade-3 "},
     {"Glade", "glade "},
     {"IonicLab", "/opt/IonicLab/IonicLab", "///opt/IonicLab/img/ionic.png" },
     {"KAppTemplate", "kapptemplate"},
     {"KCachegrind", "kcachegrind -caption KCachegrind "},
     {"KUIViewer", "kuiviewer -caption KUIViewer"},
     {"Kompare", "kompare -o "},
     {"Pingendo", "/opt/pingendo/Pingendo"},
     {"Plasma Theme Explorer", "plasmathemeexplorer"},
     {"PyAlaMode", "pyalamode", "/usr/share/pixmaps/PyCrust.png" },
     {"PyCrust", "pycrust", "/usr/share/pixmaps/PyCrust.png" },
     {"PyShell", "pyshell", "/usr/share/pixmaps/PyCrust.png" },
     {"PySlices", "pyslices", "/usr/share/pixmaps/PySlices.png" },
     {"PySlicesShell", "pysliceshell", "/usr/share/pixmaps/PySlices.png" },
     {"Qt4 Assistant", "assistant"},
     {"Qt4 Designer", "designer"},
     {"Qt4 Linguist", "linguist"},
     {"Qt5 Assistant ", "assistant-qt5 -qt=5"},
     {"Qt5 Designer", "designer-qt5 -qt=5"},
     {"Qt5 Linguist ", "linguist-qt5 -qt=5"},
     {"Qt5 QDbusViewer ", "qdbusviewer-qt5"},
     {"Umbrello", "umbrello  -caption Umbrello"},
     {"VStudio", "/opt/VStudio/vstudio ", "///opt/VStudio/Resources/vstudio.png" },
     {"XRCed", "xrced", "/usr/share/pixmaps/XRCed.png" },
     {"distcc monitor", "distccmon-gnome"},
 }

  menu3a08e2e340ab29fd9263af48193cbf8e = {      {"KHangMan", "khangman -caption KHangMan "},
      {"KLettres", "klettres -qwindowtitle KLettres "},
      {"KWordQuiz", "kwordquiz  -qwindowtitle KWordQuiz "},
      {"Kanagram", "kanagram"},
      {"Kiten", "kiten -qwindowtitle Kiten "},
      {"Parley", "parley "},
  }

  menu540b21ecdb276f5087ee585cedd6d5d0 = {      {"Cantor", "cantor  -qwindowtitle Cantor "},
      {"KAlgebra", "kalgebra "},
      {"KAlgebra Mobile", "kalgebramobile "},
      {"KBruch", "kbruch -qwindowtitle KBruch "},
      {"Kig", "kig  --qwindowtitle Kig"},
      {"KmPlot", "kmplot "},
      {"Rocs", "rocs  -qwindowtitle Rocs"},
  }

  menu387baf0199e7c9cc944fae94e96448fa = {      {"Artikulate", "artikulate -caption Artikulate "},
      {"Blinken", "blinken"},
      {"KGeography", "kgeography"},
      {"KTouch", "ktouch -caption KTouch "},
      {"KTurtle", "kturtle -qwindowtitle KTurtle"},
      {"Step", "step -qwindowtitle Step "},
  }

  menu35bf1210e6727959a7a88a00462db959 = {      {"Cantor", "cantor  -qwindowtitle Cantor "},
      {"KAlgebra", "kalgebra "},
      {"KAlgebra Mobile", "kalgebramobile "},
      {"KDE Marble", "marble "},
      {"KStars", "kstars "},
      {"Kalzium", "kalzium -caption Kalzium "},
      {"Marble", "marble-qt "},
      {"Rocs", "rocs  -qwindowtitle Rocs"},
  }

 menude7a22a0c94aa64ba2449e520aa20c99 = {    {"Languages", menu3a08e2e340ab29fd9263af48193cbf8e},
    {"Mathematics", menu540b21ecdb276f5087ee585cedd6d5d0},
    {"Miscellaneous", menu387baf0199e7c9cc944fae94e96448fa},
    {"Science", menu35bf1210e6727959a7a88a00462db959},
 }

  menuee1dde1e718954c9d03109f34f7cb3b6 = {      {"Bomber", "bomber -qwindowtitle Bomber"},
      {"Granatier", "granatier"},
      {"KBlocks", "kblocks -qwindowtitle KBlocks"},
      {"KBounce", "kbounce -qwindowtitle KBounce"},
      {"KBreakOut", "kbreakout -qwindowtitle KBreakOut"},
      {"KGoldrunner", "kgoldrunner"},
      {"KSnakeDuel", "ksnakeduel -caption KSnakeDuel "},
      {"KSpaceDuel", "kspaceduel -caption KSpaceDuel"},
      {"Kapman", "kapman"},
      {"Kolf", "kolf "},
      {"Kollision", "kollision"},
  }

  menu86798f0908c206060971bf3f7d88f00b = {      {"Bovo", "bovo -qwindowtitle Bovo"},
      {"KBlackBox", "kblackbox -qwindowtitle KBlackBox"},
      {"KFourInLine", "kfourinline"},
      {"KMahjongg", "kmahjongg -qwindowtitle KMahjongg"},
      {"KReversi", "kreversi -caption KReversi"},
      {"KSquares", "ksquares  -qwindowtitle KSquares"},
      {"Kajongg", "kajongg"},
      {"Kigo", "kigo  -caption Kigo"},
      {"Kiriki", "kiriki -qwindowtitle Kiriki"},
      {"Shisen-Sho", "kshisen -qwindowtitle Shisen-Sho"},
  }

  menu4deac91385b9f89d5630fb506dd89370 = {      {"KPatience", "kpat -qwindowtitle KPatience "},
      {"LSkat", "lskat"},
  }

  menud05008f5fed49c3c42398a6c03f0499e = {      {"Blinken", "blinken"},
      {"KHangMan", "khangman -caption KHangMan "},
      {"Kanagram", "kanagram"},
      {"Potato Guy", "ktuberling -qwindowtitle Potato Guy "},
  }

  menuaf2e9c6bed80b96a775f4ad83346abf9 = {      {"KDiamond", "kdiamond -qwindowtitle KDiamond"},
      {"KSudoku", "ksudoku  -caption KSudoku"},
      {"Kubrick", "kubrick"},
      {"Palapeli", "palapeli"},
      {"picmi", "picmi"},
  }

  menu4d1bfd4d1b44d371d9c5893282e8443b = {      {"KAtomic", "katomic -qwindowtitle KAtomic"},
      {"KJumpingCube", "kjumpingcube -qwindowtitle KJumpingCube"},
      {"KMines", "kmines -qwindowtitle KMines"},
      {"KNetWalk", "knetwalk -qwindowtitle KNetWalk"},
      {"Killbots", "killbots -qwindowtitle Killbots"},
      {"Klickety", "klickety -qwindowtitle Klickety"},
      {"Kolor Lines", "klines -qwindowtitle Kolor Lines"},
      {"Konquest", "konquest -caption Konquest"},
      {"KsirK", "ksirk -caption KsirK "},
      {"KsirK Skin Editor", "ksirkskineditor -caption KsirK Skin Editor "},
      {"Naval Battle", "knavalbattle -qwindowtitle Naval Battle "},
      {"SameGame", "klickety --KSameMode -qwindowtitle SameGame"},
  }

 menu251bd8143891238ecedc306508e29017 = {    {"Arcade", menuee1dde1e718954c9d03109f34f7cb3b6},
    {"Board Games", menu86798f0908c206060971bf3f7d88f00b},
    {"Card Games", menu4deac91385b9f89d5630fb506dd89370},
    {"Games for Kids", menud05008f5fed49c3c42398a6c03f0499e},
    {"Logic Games", menuaf2e9c6bed80b96a775f4ad83346abf9},
    {"Tactics & Strategy", menu4d1bfd4d1b44d371d9c5893282e8443b},
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
 }

  menudf05b08b23f04ad470feda13de86ca6a = {      {"KColorChooser", "kcolorchooser"},
      {"KRuler", "kruler"},
  }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {    {"More Applications", menudf05b08b23f04ad470feda13de86ca6a},
     {"Document Viewer", "evince "},
     {"GNU Image Manipulation Program", "gimp-2.8 "},
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Gwenview", "gwenview "},
     {"Inkscape", "inkscape "},
     {"KolourPaint", "kolourpaint "},
     {"Master PDF Editor 3", "/opt/master-pdf-editor-3/masterpdfeditor3 ", "///opt/master-pdf-editor-3/masterpdfeditor3.png" },
     {"Okular", "okular   -caption Okular"},
     {"Simple Scan", "simple-scan"},
     {"feh", "feh ", "///usr/share/feh/images/feh.png" },
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Akregator", "akregator "},
     {"Blogilo", "blogilo"},
     {"Chromium", "chromium "},
     {"Cloud Storage Manager", "storageservicemanager"},
     {"Contact Print Theme Editor", "contactprintthemeeditor"},
     {"Contact Theme Editor", "contactthemeeditor"},
     {"DBPedia References", "krubyapplication dbpedia_references/dbpedia_references.rb"},
     {"Firefox", "firefox ", "/usr/share/pixmaps/firefox.png" },
     {"HexChat", "hexchat --existing "},
     {"IM Contacts", "ktp-contactlist "},
     {"KDE Connect Monitor", "plasmawindowed org.kde.kdeconnect --statusnotifier"},
     {"KDE IM Log Viewer", "ktp-log-viewer "},
     {"KGet", "kget -caption KGet  "},
     {"KMail", "kmail -qwindowtitle KMail "},
     {"KMail Header Theme Editor", "headerthemeeditor"},
     {"KPPP", "kppp"},
     {"KRDC", "krdc -qwindowtitle KRDC "},
     {"KTnef", "ktnef "},
     {"KTorrent", "ktorrent "},
     {"Konqueror", "kfmclient openProfile webbrowsing"},
     {"Kopete", "kopete -caption Kopete "},
     {"Krfb", "krfb -qwindowtitle Krfb "},
     {"Opera developer", "opera-developer ", "/usr/share/pixmaps/opera-developer.xpm" },
     {"PIM Setting Exporter", "pimsettingexporter"},
     {"Pidgin Internet Messenger", "pidgin"},
     {"Qtransmission Bittorrent Client", "transmission-qt ", "/usr/share/pixmaps/transmission-qt.png" },
     {"SSH AskPass", "/usr/bin/ssh-add"},
     {"Sieve Editor", "sieveeditor"},
     {"Steam", "/usr/bin/steam ", "/usr/share/pixmaps/steam.png" },
     {"TeamViewer 11", "/opt/teamviewer/tv_bin/script/teamviewer", "///opt/teamviewer/tv_bin/desktop/teamviewer.png" },
     {"Thunderbird", "thunderbird", "///usr/share/pixmaps/thunderbird.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Vidalia", "vidalia"},
     {"XChat IRC", "xchat", "/usr/share/pixmaps/xchat.png" },
     {"Xdman", "xdman", "///usr/share/pixmaps/xdman.png" },
     {"Youtube-dlG", "youtube-dl-gui", "/usr/share/pixmaps/youtube-dl-gui.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"gFTP", "gftp ", "/usr/share/pixmaps/gftp.png" },
     {"wpa_gui", "kdesu wpa_gui", "/usr/share/pixmaps/wpa_gui.png" },
 }

 menu1c1ecba6ad0b80ad52f0a2c15c785259 = {     {"Dukto", "/usr/bin/dukto", "/usr/share/pixmaps/dukto.png" },
     {"Telegram", "/usr/bin/chromium --profile-directory=Default --app-id=clhhggbfdinjmjhajaheehoeibfljjno"},
     {"Turbo Download Manager", "/usr/bin/chromium --profile-directory=Default --app-id=kemfccojgjoilhfmcblgimbggikekjip"},
     {"VSCode", "/opt/VSCode/bin/code", "///opt/VSCode/resources/app/resources/linux/code.png" },
 }

 menu2f56b4f336dc97edf739bf79523fb9a6 = {     {"Audacious", "audacious "},
     {"Audacity", "audacity", "/usr/share/pixmaps/audacity.xpm" },
     {"Exaile", "exaile ", "/usr/share/pixmaps/exaile.png" },
     {"MPlayer", "gmplayer "},
     {"Plasma Media Center", "plasmashell -ap org.kde.plasma.mediacenter"},
     {"PulseAudio Volume Control", "pavucontrol"},
     {"Qt V4L2 test Utility", "qv4l2"},
     {"SMPlayer", "smplayer "},
     {"Webcam Application", "wxcam", "/usr/share/pixmaps/wxcam.png" },
     {"qt-recordMyDesktop", "qt-recordMyDesktop", "/usr/share/pixmaps/qt-recordmydesktop.png" },
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"Cloud Storage Manager", "storageservicemanager"},
     {"Contact Print Theme Editor", "contactprintthemeeditor"},
     {"Contact Theme Editor", "contactthemeeditor"},
     {"Document Viewer", "evince "},
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"KAddressBook", "kaddressbook "},
     {"KMail", "kmail -qwindowtitle KMail "},
     {"KMail Header Theme Editor", "headerthemeeditor"},
     {"KOrganizer", "korganizer "},
     {"KTnef", "ktnef "},
     {"Kontact", "kontact"},
     {"Lokalize", "lokalize "},
     {"Master PDF Editor 3", "/opt/master-pdf-editor-3/masterpdfeditor3 ", "///opt/master-pdf-editor-3/masterpdfeditor3.png" },
     {"Okular", "okular   -caption Okular"},
     {"PIM Setting Exporter", "pimsettingexporter"},
     {"Sieve Editor", "sieveeditor"},
     {"Txt2tags", "txt2tags --gui", "/usr/share/pixmaps/txt2tags.png" },
     {"WPS Presentation", "/usr/bin/wpp "},
     {"WPS Spreadsheets", "/usr/bin/et "},
     {"WPS Writer", "/usr/bin/wps "},
 }

 menuf4f70727dc34561dfde1a3c529b6205c = {     {"Adobe Flash Player", "flash-player-properties", "/usr/share/pixmaps/flash-player-properties.png" },
     {"Bluetooth Manager", "blueman-manager"},
     {"Customize Look and Feel", "lxappearance"},
     {"File Manager", "thunar-settings"},
     {"Gslapt Package Manager", "/usr/sbin/gslapt", "///usr/share/pixmaps/gslapt.png" },
     {"IcedTea-Web Control Panel", "/usr/bin/itweb-settings", "/usr/share/pixmaps/javaws.png" },
     {"Java", "jcontrol"},
     {"KDE Connect Settings", "kcmshell5 kcm_kdeconnect"},
     {"KDE System Settings", "systemsettings5"},
     {"Menu Editor", "/usr/bin/menulibre", "/usr/share/pixmaps/menu-editor.png" },
     {"NVIDIA X Server Settings", "/usr/bin/nvidia-settings", "///usr/share/doc/NVIDIA_GLX-1.0/nvidia-settings.png" },
     {"Network Connections", "nm-connection-editor"},
     {"Openbox Configuration Manager", "obconf ", "/usr/share/pixmaps/obconf.png" },
     {"Print Settings", "system-config-printer"},
     {"Qt4 Config", "qtconfig"},
     {"Removable Drives and Media", "thunar-volman-settings"},
     {"SCIM Input Method Setup", "scim-setup", "///usr/share/pixmaps/scim-setup.png" },
     {"Screensaver", "xscreensaver-demo", "/usr/share/pixmaps/xscreensaver.xpm" },
     {"Window Effects", "compton-conf"},
     {"Xfce-Theme-Manager", "xfce-theme-manager", "/usr/share/pixmaps/xfce-theme-manager.png" },
 }

 menua45da96d0bf6575970f2d27af22be28a = {     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename "},
     {"Dolphin", "dolphin "},
     {"GParted", "/usr/sbin/gparted_polkit "},
     {"Genymotion", "/opt/genymotion/genymotion", "///home/andre/genymotion/icons/icon.png" },
     {"Gslapt Package Manager", "/usr/sbin/gslapt", "///usr/share/pixmaps/gslapt.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KDiskFree", "kdf -caption KDiskFree"},
     {"KSysGuard", "ksysguard "},
     {"KSystemLog", "xdg_menu_su ksystemlog -qwindowtitle KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser"},
     {"KWalletManager", "kwalletmanager5 "},
     {"Konsole", "konsole"},
     {"Krfb", "krfb -qwindowtitle Krfb "},
     {"KwikDisk", "kwikdisk -caption KwikDisk"},
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/"},
     {"Menu Editor", "/usr/bin/menulibre", "/usr/share/pixmaps/menu-editor.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/pixmaps/virtualbox.png" },
     {"P7ZIP File Manager", "7zFM ", "/usr/share/pixmaps/p7zip.png" },
     {"Print Settings", "system-config-printer"},
     {"SSH AskPass", "/usr/bin/ssh-add"},
     {"Terminator", "terminator", "/usr/share/pixmaps/terminator.png" },
     {"Thunar File Manager", "thunar "},
     {"Tint2 panel", "tint2"},
     {"Wireshark", "wireshark "},
     {"Wireshark (GTK+)", "wireshark-gtk "},
     {"dconf Editor", "dconf-editor"},
     {"urxvt", "urxvt"},
 }

 menuceba282b7418b7f199798b645e1cba56 = {     {"Archive Manager", "file-roller "},
     {"Ark", "ark "},
     {"Atom", "/usr/bin/atom "},
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename "},
     {"Character Map", "gucharmap"},
     {"Filelight", "filelight "},
     {"GVim", "gvim -f "},
     {"Galculator", "galculator", "/usr/share/pixmaps/galculator.xpm" },
     {"KAlarm", "kalarm"},
     {"KCalc", "kcalc"},
     {"KCharSelect", "kcharselect --qwindowtitle KCharSelect"},
     {"KDebugSettings", "kdebugsettings"},
     {"KFileReplace", "kfilereplace  -caption KFileReplace"},
     {"KFloppy", "kfloppy -qwindowtitle KFloppy"},
     {"KGpg", "kgpg "},
     {"KJots", "kjots -caption KJots"},
     {"KMag", "kmag -caption KMag "},
     {"KMail Import Wizard", "importwizard"},
     {"KMouseTool", "kmousetool -caption KMouseTool "},
     {"KMouth", "kmouth -caption KMouth "},
     {"KNotes", "knotes"},
     {"KTeaTime", "kteatime"},
     {"KTimer", "ktimer"},
     {"KTnef", "ktnef "},
     {"KWrite", "kwrite "},
     {"Kate", "kate -b "},
     {"Kleopatra", "kleopatra"},
     {"Leafpad", "leafpad ", "/usr/share/pixmaps/leafpad.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Okteta", "okteta "},
     {"Okteta", "okteta -caption Okteta "},
     {"P7ZIP File Manager", "7zFM ", "/usr/share/pixmaps/p7zip.png" },
     {"Root Terminal", "gksu /usr/bin/terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"SCIM (Smart Common Input Method) startup", "scim -d", "///usr/share/pixmaps/scim-setup.png" },
     {"Spectacle", "spectacle"},
     {"Sublime Text", "sublime_text", "/usr/share/pixmaps/sublime_text.png" },
     {"Sweeper", "sweeper"},
     {"Terminator", "terminator", "/usr/share/pixmaps/terminator.png" },
     {"Thunar File Manager", "thunar "},
     {"Vim", "xterm -e vim "},
     {"compton", "compton"},
     {"gpa", "gpa", "/usr/share/pixmaps/gpa.png" },
 }

xdgmenu = {    {"Development", menu330f49df8243756a8a4dc7f7f7ee6dfe},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Lost & Found", menu1c1ecba6ad0b80ad52f0a2c15c785259},
    {"Multimedia", menu2f56b4f336dc97edf739bf79523fb9a6},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Settings", menuf4f70727dc34561dfde1a3c529b6205c},
    {"System", menua45da96d0bf6575970f2d27af22be28a},
    {"Utilities", menuceba282b7418b7f199798b645e1cba56},
}

